# Generated by Django 2.0 on 2017-12-15 20:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type_id', models.IntegerField(verbose_name='Content type')),
                ('object_id', models.IntegerField(verbose_name='Object id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date of modification')),
                ('content', models.TextField(max_length=5000, verbose_name='Content')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is edited')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User', verbose_name='Author')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.Comment', verbose_name='Parent comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Updated'), (2, 'Deleted')], verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='comments.Comment', verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_history', to='users.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comment history',
            },
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('content_type_id', 'object_id')},
        ),
    ]
