# Generated by Django 2.0 on 2017-12-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20171217_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment history', 'verbose_name_plural': 'Comments history'},
        ),
    ]
