# Generated by Django 2.0 on 2017-12-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20171217_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is deleted'),
        ),
    ]
