# Generated by Django 2.0 on 2017-12-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20171217_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date of creation'),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('content_type_id', 'object_id', 'is_deleted'), ('tree_id', 'lft')},
        ),
    ]
