# Generated by Django 2.0 on 2017-12-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20171218_1441'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('content_type_id', 'object_id', 'is_deleted'), ('tree_id', 'lft'), ('content_type_id', 'object_id')},
        ),
    ]
