version: '3'

services:
  test:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    volumes:
      - .:/app
      - ./compose/web/runtest.sh:/runtest.sh
    env_file:
      - ./example.env
    links:
      - db:db
    depends_on:
      - db
    command: /runtest.sh